def create_brands
    elements = [
        '3M',
        'Alienware',
        'Amazon',
        'AMD',
        'Analog Devices',
        'Apple',
        'Audiovox',
        'Avaya',
        'Averatec',
        'Bose',
        'Cisco Systems',
        'Crucial Technology',
        'Dell',
        'eMachines',
        'Emerson Electric',
        'Emerson Radio',
        'Fitbit',
        'Gateway',
        'Google',
        'Hewlett-Packard',
        'HP',
        'IBM',
        'Intel',
        'JBL',
        'Kingston',
        'Koss',
        'Magnavox',
        'Micron Technology',
        'Microsoft',
        'Motorola Mobility',
        'Nvidia',
        'Packard Bell',
        'Plantronics',
        'Polycom',
        'Qualcomm',
        'RCA',
        'Sandisk',
        'Seagate',
        'SGI',
        'Sun Microsystems',
        'Texas Instruments',
        'Unisonic Products Corporation',
        'Unisys',
        'Vizio',
        'Viewsonic',
        'Western Digital',
        'Westinghouse Electric Corporation',
        'Xerox',
        'Zenith',
        'Aigo',
        'Amoi',
        'BYD Electronic',
        'Changhong',
        'Gionee',
        'Haier',
        'Hasee',
        'Hisense',
        'Huawei',
        'Konka Group',
        'Meizu',
        'Ningbo Bird',
        'Oppo',
        'Panda',
        'Skyworth',
        'TCL',
        'TP-Link/intex',
        'Vivo Electronics',
        'Zopo Mobile',
        'ZTE',
        'Xiaomi',
        'OnePlus',
        'Allied Telesis – NW, OEE',
        'Alpine',
        'Atari',
        'Brother Industries',
        'Buffalo',
        'Canon',
        'Casio',
        'Clarion',
        'Eclipse',
        'Eizo ',
        'Epson',
        'Fuji Electric ',
        'Fuji Xerox',
        'Fujifilm',
        'Fujitsu',
        'Funai',
        'Hitachi',
        'Iiyama ',
        'JVC',
        'Kenwood',
        'Konica Minolta',
        'Kyocera ',
        'Marantz',
        'Mitsubishi',
        'NEC',
        'Nikon ',
        'Nintendo',
        'Oki',
        'Olympus',
        'Orion',
        'Panasonic',
        'Pentax',
        'Pioneer',
        'Renesas ',
        'Ricoh ',
        'Sansui Electric',
        'Sega Corporation',
        'Sharp',
        'SII',
        'SNK Corporation',
        'Sony',
        'TDK',
        'Toshiba',
        'Victor',
        'Yaesu',
        'Cowon',
        'Daewoo Electronics',
        'Hansol',
        'Iriver',
        'LG',
        'Pantech',
        'Samsung',
        'Kyocera',
        'Hyundai',
        'Acer',
        'AOC ',
        'Aopen',
        'Asus',
        'BenQ',
        'D-Link',
        'ECS',
        'Elsa',
        'EPoX',
        'Foxconn',
        'Gigabyte',
        'HTC',
        'Lite-On',
        'MediaTek',
        'MSI',
        'Realtek',
        'Silicon Power',
        'Soyo',
        'Surya',
        'Transcend',
        'TSMC',
        'VIA Technologies',
        'Alcatel-Lucent',
        'Thomson Broadcast',
        'Blaupunkt',
        'Bosch',
        'Braun',
        'Grundig',
        'Loewe AG',
        'Medion',
        'Metz',
        'Miele',
        'Siemens',
        'Sennheiser',
        'Severin Elektro',
        'TechniSat',
        'Telefunken',
        'Wortmann',
        'Philips',
        'Trust',
    ]

    puts 'Seeding brands...'
    elements.each do |element|
        brand = Brand.create(name: element, slug: element.parameterize, activated: true)
        brand.image.attach(io: File.open("app/assets/images/brand.jpg"), filename: 'brand.jpg',  identify: false)
    end

    puts "#{elements.count} brands seeded"
end