def create_categories
    categories = [
        {'Agriculture & Food': [
            'Agricultural Waste',
            'Animal Products',
            'Beans',
            'Cocoa Beans',
            'Coffee Beans',
            'Farm Machinery & Equipment',
            'Feed',
            'Fresh Seafood',
            'Fruit',
            'Grain',
            'Herbal Cigars & Cigarettes',
            'Mushrooms & Truffles',
            'Nuts & Kernels',
            'Ornamental Plants',
            'Other Agriculture Products',
            'Plant & Animal Oil',
            'Plant Seeds & Bulbs',
            'Timber Raw Materials',
            'Vanilla Beans',
            'Vegetables',
            'Alcoholic Beverage',
            'Baby Food',
            'Baked Goods',
            'Bean Products',
            'Canned Food',
            'Coffee',
            'Confectionery',
            'Dairy',
            'Drinking Water',
            'Egg & Egg Products',
            'Food Ingredients',
            'Fruit Products',
            'Grain Products',
            'Honey Products',
            'Instant Food',
            'Meat & Poultry',
            'Other Food & Beverage',
            'Seafood',
            'Seasonings & Condiments',
            'Snack Food',
            'Soft Drinks',
            'Tea',
            'Vegetable Products',
        ]},
        {'Apparel,Textiles & Accessories':[
            "Apparel Design Services",
            "Apparel Processing Services",
            "Apparel Stock",
            "Boy's Clothing",
            "Costumes",
            "Ethnic Clothing",
            "Garment Accessories",
            "Girl‘s Clothing",
            "Infant & Toddlers Clothing",
            "Mannequins",
            "Maternity Clothing",
            "Men‘s Clothing",
            "Sewing Supplies",
            "Sportswear",
            "Stage & Dance Wear",
            "Tag Guns",
            "Uniforms",
            "Used Clothes",
            "Wedding Apparel & Accessories",
            "Women's Clothing",
            "Down & Feather",
            "Fabric",
            "Fiber",
            "Fur",
            "Grey Fabric",
            "Home Textile",
            "Leather",
            "Leather Product",
            "Other Textiles & Leather Products",
            "Textile Accessories",
            "Textile Processing",
            "Thread",
            "Yarn",
            "100% Cotton Fabric",
            "100% Polyester Fabric",
            "Bedding Set",
            "Towel",
            "Chair Cover",
            "Genuine Leather",
            "Belt Accessories",
            "Belts",
            "Fashion Accessories Design Services",
            "Fashion Accessories Processing Services",
            "Gloves & Mittens",
            "Scarf, Hat & Glove Sets",
            "Hats & Caps",
            "Scarves & Shawls",
            "Hair Accessories",
            "Genuine Leather Belts",
            "Leather Gloves & Mittens",
            "Ties & Accessories",
            "Belt Buckles",
            "PU Belts",
            "Belt Chains",
            "Metal Belts",
            "Suspenders",
            "Eyewear",
            "Jewelry",
            "Watches",
            "Eyeglasses Frames",
            "Sunglasses",
            "Sports Eyewear",
            "Body Jewelry",
            "Bracelets & Bangles",
            "Brooches",
            "Cuff Links & Tie Clips",
            "Earrings",
            "Jewelry Boxes",
            "Jewelry Sets",
            "Jewelry Tools & Equipment",
            "Loose Beads",
            "Loose Gemstone",
            "Necklaces",
            "Pendants & Charms",
            "Rings",
            "Wristwatches",
        ]},
        {'Auto & Transportation':[
            'Automobiles',
            'Trailers',
            'Trucks',
            'Golf Carts',
            'Marine Parts & Accessories',
            'Truck Parts & Accessories',
            'Trains',
            'Motorcycles & Scooters',
            'Auto Parts & Accessories',
            'Emergency Vehicles',
            'Bus Parts & Accessories',
            'ATVs & UTVs',
            'Bus',
            'Containers',
            'Other Vehicle Parts & Accessories',
            'Other Vehicles',
        ]},
        {'Bags, Shoes & Accessories':[
            "Bag & Luggage Making Materials",
            "Bag Parts & Accessories",
            "Business Bags & Cases",
            "Digital Gear & Camera Bags",
            "Handbags & Messenger Bags",
            "Luggage & Travel Bags",
            "Luggage Cart",
            "Other Luggage, Bags & Cases",
            "Special Purpose Bags & Cases",
            "Sports & Leisure Bags",
            "Wallets & Holders",
            "Carry-on Luggage",
            "Luggage Sets",
            "Trolley Bags",
            "Briefcases",
            "Cosmetic Bags & Cases",
            "Shopping Bags",
            "Handbags",
            "Backpacks",
            "Wallets",
        ]},
        {'Electronics':[
            'Computer Hardware & Software',
            'Electronic Cigarettes',
            'Accessories & Parts',
            'Camera, Photo & Accessories',
            'Electronic Publications',
            'Home Audio, Video & Accessories',
            'Mobile Phone & Accessories',
            'Other Consumer Electronics',
            'Portable Audio, Video & Accessories',
            'Video Game & Accessories',
            'Mobile Phones',
            'Earphone & Headphone',
            'Power Banks',
            'Digital Camera',
            'Radio & TV Accessories',
            'Speaker',
            'Television',
            'Cables',
            'Charger',
            'Digital Battery',
            'Digital Photo Frame',
            '3D Glasses',
            'Air Conditioning Appliances',
            'Cleaning Appliances',
            'Hand Dryers',
            'Home Appliance Parts',
            'Home Appliances Stocks',
            'Home Heaters',
            'Kitchen Appliances',
            'Laundry Appliances',
            'Other Home Appliances',
            'Refrigerators & Freezers',
            'Water Heaters',
            'Water Treatment Appliances',
            'Wet Towel Dispensers',
            'Air Conditioners',
            'Fans',
            'Vacuum Cleaners',
            'Solar Water Heaters',
            'Cooking Appliances',
            'Coffee Makers',
            'Blenders',
            'Locks & Keys',
            'Personal Protective Equipment',
            'Access Control Systems & Products',
            'Alarm',
            'CCTV Products',
            'Firefighting Supplies',
            'Locksmith Supplies',
            'Other Security & Protection Products',
            'Police & Military Supplies',
            'Roadway Safety',
            'Safes',
            'Security Services',
            'Self Defense Supplies',
            'Water Safety Products',
            'CCTV Camera',
            'Bullet Proof Vest',
            'Alcohol Tester',
            'Fire Alarm',
        ]},
        {'Electrical Equipment, Components & Telecoms':[
            'Solar Energy Products',
            'Batteries',
            'Electrical Instruments',
            'Circuit Breakers',
            'Connectors & Terminals',
            'Industrial Controls',
            'Contactors',
            'Motors',
            'Electrical Supplies',
            'Electronic & Instrument Enclosures',
            'Fuse Components',
            'Fuses',
            'Generators',
            'Power Accessories',
            'Power Distribution Equipment',
            'Power Supplies',
            'Professional Audio, Video & Lighting',
            'Relays',
            'Switches',
            'Transformers',
            'Wires, Cables & Cable Assemblies',
            'Wiring Accessories',
            'Solar Cells, Solar Panel',
        ]},
        {'Gifts, Sports & Toys':[
            'Sports & Entertainment',
            'Amusement Park',
            'Artificial Grass & Sports Flooring',
            'Fitness & Body Building',
            'Gambling',
            'Golf',
            'Indoor Sports',
            'Musical Instruments',
            'Other Sports & Entertainment Products',
            'Outdoor Sports',
            'Sports Gloves',
            'Sports Safety',
            'Sports Souvenirs',
            'Team Sports',
            'Tennis',
            'Water Sports',
            'Winter Sports',
            'Camping & Hiking',
            'Scooters',
            'Gym Equipment',
            'Swimming & Diving',
            'Gifts & Crafts',
            'Art & Collectible',
            'Crafts',
            'Arts & Crafts Stocks',
            'Cross Stitch',
            'Festive & Party Supplies',
            'Flags, Banners & Accessories',
            'Gift Sets',
            'Holiday Gifts',
            'Home Decoration',
            'Key Chains',
            'Knitting & Crocheting',
            'Lacquerware',
            'Lanyard',
            'Money Boxes',
            'Music Boxes',
            'Pottery & Enamel',
            'Sculptures',
            'Souvenirs',
            'Stickers',
            'Wedding Decorations & Gifts',
            'Toys & Hobbies',
            'Action Figure',
            'Baby Toys',
            'Balloons',
            'Candy Toys',
            'Classic Toys',
            'Dolls',
            'Educational Toys',
            'Electronic Toys',
            'Glass Marbles',
            'Inflatable Toys',
            'Light-Up Toys',
            'Noise Maker',
            'Other Toys & Hobbies',
            'Outdoor Toys & Structures',
            'Plastic Toys',
            'Pretend Play & Preschool',
            'Solar Toys',
            'Toy Accessories',
            'Toy Animal',
            'Toy Guns',
            'Toy Parts',
            'Toy Robots',
            'Toy Vehicle',
            'Wind Up Toys',
            'Wooden Toys',
            'Less',
            
        ]},
        {'Health & Beauty':[
            'Health & Medical',
            'Animal Extract',
            'Plant Extracts',
            'Body Weight',
            'Health Care Supplement',
            'Health Care Supplies',
            'Crude Medicine',
            'Prepared Drugs In Pieces',
            'Traditional Patented Medicines',
            'Body Fluid-Processing & Circulation Devices',
            'Clinical Analytical Instruments',
            'Dental Equipment',
            'Emergency & Clinics Apparatuses',
            'Equipments of Traditional Chinese Medicine',
            'General Assay & Diagnostic Apparatuses',
            'Medical Consumable',
            'Medical Cryogenic Equipments',
            'Medical Software',
            'Physical Therapy Equipments',
            'Radiology Equipment & Accessories',
            'Sterilization Equipments',
            'Surgical Instrument',
            'Ultrasonic, Optical, Electronic Equipment',
            'Ward Nursing Equipments',
            'Medicines',
            'View More',
            'Beauty & Personal Care',
            'Baby Care',
            'Bath Supplies',
            'Beauty Equipment',
            'Body Art',
            'Breast Care',
            'Feminine Hygiene',
            'Fragrance & Deodorant',
            'Hair Care',
            'Hair Extensions & Wigs',
            'Hair Salon Equipment',
            'Makeup',
            'Makeup Tools',
            'Men Care',
            'Nail Supplies',
            'Oral Hygiene',
            'Other Beauty & Personal Care Products',
            'Sanitary Paper',
            'Shaving & Hair Removal',
            'Skin Care',
            'Skin Care Tool',
        ]},
        {'Home, Lights & Construction':[
            'Construction & Real Estate ',
            'Aluminum Composite Panels',
            'Balustrades & Handrails',
            'Bathroom',
            'Boards',
            'Building Glass',
            'Ceilings',
            'Corner Guards',
            'Countertops,Vanity Tops & Table Tops',
            'Curtain Walls & Accessories',
            'Decorative Films',
            'Door & Window Accessories',
            'Doors & Windows',
            'Earthwork Products',
            'Elevators & Elevator Parts',
            'Escalators & Escalator Parts',
            'Faucets, Mixers & Taps',
            'Fiberglass Wall Meshes',
            'Fireplaces,Stoves',
            'Fireproofing Materials',
            'Floor Heating Systems & Parts',
            'Flooring & Accessories',
            'Formwork',
            'Gates',
            'Heat Insulation Materials',
            'HVAC Systems & Parts',
            'Kitchen',
            'Ladders & Scaffoldings',
            'Landscaping Stone',
            'Masonry Materials',
            'Metal Building Materials',
            'Mosaics',
            'Mouldings',
            'Multifunctional Materials',
            'Other Construction & Real Estate',
            'Plastic Building Materials',
            'Quarry Stone & Slabs',
            'Real Estate',
            'Soundproofing Materials',
            'Stairs & Stair Parts',
            'Stone Carvings and Sculptures',
            'Sunrooms & Glass Houses',
            'Tiles & Accessories',
            'Timber',
            'Tombstones and Monuments',
            'Wallpapers/Wall Coating',
            'Waterproofing Materials',
            'View More',
            'Home & Garden',
            'Bakeware',
            'Barware',
            'Bathroom Products',
            'Cooking Tools',
            'Cookware',
            'Garden Supplies',
            'Home Decor',
            'Home Storage & Organization',
            'Household Chemicals',
            'Household Cleaning Tools & Accessories',
            'Household Sundries',
            'Kitchen Knives & Accessories',
            'Laundry Products',
            'Pet Products',
            'Kitchen,Dining,Bar & Tableware',
            'Dinnerware',
            'Drinkware',
            'Baby Supplies & Products',
            'Rain Gear',
            'Lighters & Smoking Accessories',
            'Lights & Lighting',
            'Emergency Lighting',
            'Holiday Lighting',
            'Indoor Lighting',
            'LED Lighting',
            'Lighting Accessories',
            'Lighting Bulbs & Tubes',
            'Other Lights & Lighting Products',
            'Outdoor Lighting',
            'Professional Lighting',
            'LED Residential Lighting',
            'LED Outdoor Lighting',
            'Chandeliers & Pendant Lights',
            'Ceiling Lights',
            'Crystal Lights',
            'Stage Lights',
            'Street Lights',
            'Energy Saving & Fluorescent',
            'LED Landscape Lamps',
            'LED Professional Lighting',
            'LED Encapsulation Series',
            'Furniture',
            'Antique Furniture',
            'Baby Furniture',
            'Bamboo Furniture',
            'Children Furniture',
            'Commercial Furniture',
            'Folding Furniture',
            'Furniture Accessories',
            'Furniture Hardware',
            'Furniture Parts',
            'Glass Furniture',
            'Home Furniture',
            'Inflatable Furniture',
            'Metal Furniture',
            'Other Furniture',
            'Outdoor Furniture',
            'Plastic Furniture',
            'Rattan / Wicker Furniture',
            'Wood Furniture',
            'Living Room Furniture',
            'Bedroom Furniture',
        ]},
        {'Machinery, Industrial Parts & Tools':[
            'Machinery',
            'Agriculture Machinery & Equipment',
            'Apparel & Textile Machinery',
            'Building Material Machinery',
            'Chemical Machinery & Equipment',
            'Electronic Products Machinery',
            'Energy & Mineral Equipment',
            'Engineering & Construction Machinery',
            'Food & Beverage Machinery',
            'General Industrial Equipment',
            'Home Product Making Machinery',
            'Industry Laser Equipment',
            'Machine Tool Equipment',
            'Metal & Metallurgy Machinery',
            'Other Machinery & Industry Equipment',
            'Packaging Machine',
            'Paper Production Machinery',
            'Pharmaceutical Machinery',
            'Plastic & Rubber Machinery',
            'Printing Machine',
            'Refrigeration & Heat Exchange Equipment',
            'Used Machinery & Equipment',
            'Woodworking Machinery',
            'View More',
            'Fabrication Services',
            'Custom Fabrication Services',
            'General Mechanical Components Design Services',
            'General Mechanical Components Stock',
            'Industrial Brake',
            'Machine Tools Accessory',
            'Moulds',
            'Other General Mechanical Components',
            'Other Mechanical Parts',
            'Used General Mechanical Components',
            'Coating Services',
            'Tools & Hardware',
            'Hardware',
            'Hand Tools',
            'Material Handling Tools',
            'Power Tool Accessories',
            'Power Tools',
            'Tool Design Services',
            'Tool Parts',
            'Tool Processing Services',
            'Tool Sets',
            'Tool Stock',
            'Knife',
            'Hand Carts & Trolleys',
            'Lawn Mower',
            'Sander',
            
        ]},
        {'Metallurgy, Chemicals, Rubber & Plastics':[
            'Minerals & Metallurgy',
            'Aluminum',
            'Barbed Wire',
            'Billets',
            'Carbon',
            'Carbon Fiber',
            'Cast & Forged',
            'Cemented Carbide',
            'Ceramic Fiber Products',
            'Ceramics',
            'Copper',
            'Copper Forged',
            'Fiberglass Products',
            'Glass',
            'Graphite Products',
            'Ingots',
            'Iron',
            'Lead',
            'Lime',
            'Magnetic Materials',
            'Metal Scrap',
            'Metal Slabs',
            'Mineral Wool',
            'Molybdenum',
            'Nickel',
            'Non-Metallic Mineral Deposit',
            'Ore',
            'Other Metals & Metal Products',
            'Other Non-Metallic Minerals & Products',
            'Pig Iron',
            'Quartz Products',
            'Rare Earth & Products',
            'Rare Earth Magnets',
            'Refractory',
            'Steel',
            'Titanium',
            'Tungsten',
            'Wire Mesh',
            'Zinc',
            'View More',
            'Chemicals',
            'Gas Disposal',
            'Noise Reduction Device',
            'Other Environmental Products',
            'Other Excess Inventory',
            'Recycling',
            'Sewer',
            'Waste Management',
            'Water Treatment',
            'Textile Waste',
            'Waste Paper',
            'Other Recycling Products',
            'Rubber & Plastics',
            'Plastic Processing Service',
            'Plastic Products',
            'Plastic Projects',
            'Plastic Raw Materials',
            'Plastic Stocks',
            'Recycled Plastic',
            'Recycled Rubber',
            'Rubber Processing Service',
            'Rubber Products',
            'Rubber Projects',
            'Rubber Raw Materials',
            'Rubber Stocks',
            'Plastic Cards',
            'PVC',
            'Plastic Tubes',
            'HDPE',
            'Rubber Hoses',
            'Plastic Sheets',
            'LDPE',
            'Agricultural Rubber',
            'Energy',
            'Biodiesel',
            'Biogas',
            'Charcoal',
            'Coal',
            'Coal Gas',
            'Coke Fuel',
            'Crude Oil',
            'Electricity Generation',
            'Petrochemical Products',
            'Solar Energy Products',
            'Industrial Fuel',
            'Natural Gas',
            'Other Energy Related Products',
            'Wood Pellets',
            'Solar Energy Systems',
            'Lubricant',
            'Diesel Fuel',
            'Solar Collectors',
        ]},
        {'Packaging, Advertising & Office':[
            'Packaging & Printing',
            'Adhesive Tape',
            'Agricultural Packaging',
            'Aluminum Foil',
            'Apparel Packaging',
            'Blister Cards',
            'Bottles',
            'Cans',
            'Chemical Packaging',
            'Composite Packaging Materials',
            'Cosmetics Packaging',
            'Electronics Packaging',
            'Food Packaging',
            'Gift Packaging',
            'Handles',
            'Hot Stamping Foil',
            'Jars',
            'Lids, Bottle Caps, Closures',
            'Media Packaging',
            'Metallized Film',
            'Other Packaging Applications',
            'Other Packaging Materials',
            'Packaging Bags',
            'Packaging Boxes',
            'Packaging Labels',
            'Packaging Trays',
            'Packaging Tubes',
            'Paper & Paperboard',
            'Paper Packaging',
            'Pharmaceutical Packaging',
            'Plastic Film',
            'Plastic Packaging',
            'Printing Materials',
            'Printing Services',
            'Protective Packaging',
            'Pulp',
            'Shrink Film',
            'Strapping',
            'Stretch Film',
            'Tobacco Packaging',
            'Transport Packaging',
            'View More',
            'Office & School Supplies',
            'Art Supplies',
            'Badge Holder & Accessories',
            'Board',
            'Board Eraser',
            'Book Cover',
            'Books',
            'Calculator',
            'Calendar',
            'Clipboard',
            'Correction Supplies',
            'Desk Organizer',
            'Drafting Supplies',
            'Easels',
            'Educational Supplies',
            'Filing Products',
            'Letter Pad / Paper',
            'Magazines',
            'Map',
            'Notebooks & Writing Pads',
            'Office Adhesives & Tapes',
            'Office Binding Supplies',
            'Office Cutting Supplies',
            'Office Equipment',
            'Office Paper',
            'Other Office & School Supplies',
            'Paper Envelopes',
            'Pencil Cases & Bags',
            'Pencil Sharpeners',
            'Printer Supplies',
            'Stamps',
            'Stationery Set',
            'Stencils',
            'Writing Accessories',
            'Writing Instruments',
            'Yellow Pages',
            'View More',
            'Service Equipment',
            'Advertising Equipment',
            'Cargo & Storage Equipment',
            'Commercial Laundry Equipment',
            'Financial Equipment',
            'Funeral Supplies',
            'Other Service Equipment',
            'Restaurant & Hotel Supplies',
            'Store & Supermarket Supplies',
            'Trade Show Equipment',
            'Vending Machines',
            'Wedding Supplies',
            'Display Racks',
            'Advertising Players',
            'Advertising Light Boxes',
            'Hotel Amenities',
            'POS Systems',
            'Supermarket Shelves',
            'Stacking Racks & Shelves',
            'Refrigeration Equipment',
            'Trade Show Tent',
        ]}
    ]

    images = [
        'agriculture-food/default.jpg',
        ''
    ]
    puts 'seeding categories...'
    subcat = 0
    categories.map do |category|
        cat = Category.create(name: category.keys[0].to_s, slug: category.keys[0].to_s.parameterize)
        cat.image.attach(io: File.open('app/assets/images/empty.jpg'), filename: 'empty.jpg',  identify: false)
        Subcategory.create(name: category.keys[0].to_s, slug: category.keys[0].to_s.parameterize, category_id: cat.id)
        category.values[0].map do |subcategorie|
            Subcategory.create(name: subcategorie, slug: subcategorie.parameterize, category_id: cat.id)
            subcat += 1
        end
        
    end
    puts "#{categories.count} categories seeded with #{subcat} subcategories!"
end